server:
  port: 8080

spring:
  application:
    name: api-linting
  threads:
    virtual:
      enabled: true

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true

linting:
  max-file-size: 5MB
